### ISSUE TITLE
[BUG] Cannot install in kubernetes on keycloak 21.1.1

### ISSUE THREAD

**Issue by ksawerykarwacki** [sventorben/keycloak-home-idp-discovery#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Despite the fact that this manifest works for other extensions Keycloak pod keeps crushing when installing keycloak-home-idp-discover with error:

```
ERROR: Failed to run 'build' command.
ERROR: java.io.IOException: Failed to create a new filesystem for /opt/keycloak/lib/../providers/keycloak-home-idp-discovery.jar
ERROR: Failed to create a new filesystem for /opt/keycloak/lib/../providers/keycloak-home-idp-discovery.jar
ERROR: zip END header not found
```

### Expected Behavior

Properly install extension are start working. 

### Steps To Reproduce

1. Install keycloak operator version 21.1.1
2. Apply manifest
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-cluster
  namespace: my-namespace
spec:
  additionalOptions:
    - name: health-enabled
      value: 'true'
    - name: metrics-enabled
      value: 'true'
    - name: log-level
      value: info,org.keycloak.events:trace
    - name: proxy
      value: edge
  db:
    passwordSecret:
      key: pg-password
      name: keycloak-postgres-database-postgres-secret
    schema: public
    url: >-
      jdbc:postgresql://postgres-cluster-primary.my-namespace.svc:5432/keycloak
    usernameSecret:
      key: pg-username
      name: keycloak-postgres-database-postgres-secret
    vendor: postgres
  hostname:
    admin: keycloak.example.com
    hostname: keycloak.example.com
    strict: false
  http:
    httpEnabled: true
  ingress:
    enabled: false
  instances: 1
  unsupported:
    podTemplate:
      metadata:
        labels:
          instance: keycloak-cluster
      spec:
        containers:
          - name: keycloak
            volumeMounts:
              - mountPath: /opt/keycloak/providers
                name: providers
        initContainers:
          - command:
              - sh
              - '-c'
              - >-
                curl 
                https://github.com/sventorben/keycloak-home-idp-discovery/releases/download/v21.3.0/keycloak-home-idp-discovery.jar
                --output
                /opt/keycloak/providers/keycloak-home-idp-discovery.jar
            image: curlimages/curl:8.00.1
            name: extension1
            volumeMounts:
              - mountPath: /opt/keycloak/providers
                name: providers
        volumes:
          - emptyDir: {}
            name: providers
```

### Version

```markdown
- Kyecloak operator: 21.1.1
- Keycloak: 21.1.1
- This extension: tried version 21.2.1 and 21.3.0
```

### Anything else?

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/11694791/2efc840a-9bd1-43ef-bcf2-80c13efef49d)

Problem is also present on docker with current version:

`curl https://github.com/sventorben/keycloak-home-idp-discovery/releases/download/v22.0.0/keycloak-home-idp-discovery.jar --output keycloak-home-idp-discovery.jar`

```
version: '3'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug', '--import-realm']
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8787
    volumes:
    - ./keycloak-home-idp-discovery.jar:/opt/keycloak/providers/keycloak-home-idp-discovery.jar
```
![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/11694791/5e604718-bcee-4892-92ae-cc9f8ae41820)
